# Set up an environment for running the tests.
FROM centos:8
RUN dnf -y install 'dnf-command(builddep)' https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
dnf config-manager --set-enabled PowerTools

# Add test dependencies
COPY test-packages .
RUN dnf -y install $(cat test-packages)

# pocketlint to modify pylint behavior, and Sphinx because it isn't in EPEL8
RUN pip-3 install pocketlint
