specfile_path: pykickstart.spec
upstream_package_name: pykickstart
downstream_package_name: pykickstart

srpm_build_deps:
  - git
  - gettext
  - make
  - python3-devel
  - python3-pip
  - python3-setuptools
  - python3-build
  - python3-sphinx

actions:
  get-current-version:
    - python3 setup.py --version
  create-archive:
    - make local WEBLATE_BRANCH=master
    - bash -c "ls *.tar*"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide
    branch: master

  - job: copr_build
    trigger: commit
    targets:
      - fedora-rawhide
    branch: master
    owner: "@rhinstaller"
    project: Pykickstart
    preserve_project: True
